apiVersion: v1
kind: Service
metadata:
  name: svc-lb-internal-python-django
  namespace: pipeline-dev
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: python-django

